version: "2"
services:
  apache:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/local/apache2/htdocs
      - ./modules/httpd.conf:/usr/local/apache2/conf/httpd.conf
  nginx:
    image: nginx:alpine
    ports:
      - "8880:80"
      - "8443:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./modules/default.conf:/etc/nginx/conf.d/default.conf
